### ISSUE TITLE
For 3.0 release

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-ui-icons#107]
- [x] Remove the concept of fill and outline (documentation page too)
- [x] reference pages show all icons including a fill. Multi-path icons displayed in a new tab 
- [x] Update readme to reflect changes

Please update or add anything I missed.

**Comment by johnmgriffith** [comment]
Let Katelyn and I know how we can help with this next week.

**Comment by paulcpederson** [comment]
If we want to do multi-path we should move those tasks to a new issue. The removal of filled vs outline is covered in: #114

**Comment by julio8a** [comment]
Will move to a new issue and remove from here.

**Comment by paulcpederson** [comment]
This is done and merged.
