### ISSUE TITLE
measure-area icon appears to be busted.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#108]
Looks like this
![image](https://user-images.githubusercontent.com/12503298/74868392-07dea980-530b-11ea-8c08-e28e9ac64be6.png)

Should look like this
![image](https://user-images.githubusercontent.com/12503298/74868433-1c22a680-530b-11ea-9f60-067caf70ca8f.png)

**Comment by KatelynSeitz** [comment]
Hmm I cannot seem to replicate this result on my end. Is this happening for any other sizes or icons?

**Comment by johnmgriffith** [comment]
Can you show us where you are seeing this, and what you think might be causing it?

**Comment by johnmgriffith** [comment]
Are you still encountering this problem @asangma ?

**Comment by asangma** [comment]
Thanks for following up.
