### ISSUE TITLE
Additions : Number icons

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#119]
Sorry if this has already been discussed.
We could use basic numeric concepts:

- sum
- average*
- percent
- minimum*
- maximum*

* If there are not established symbols for these, they could be treated how we're treating `int` and `bool`.

**Comment by johnmgriffith** [comment]
These seem like good concepts to add to the library. Can you take the lead on this and open a Workfront request?

**Comment by asangma** [comment]
Will do.

**Comment by johnmgriffith** [comment]
This was resolved a while ago. Closing now.
