### ISSUE TITLE
Vertical 'ellipsis'/'handle'

### ISSUE THREAD

**Issue by jordanisip** [Esri/calcite-ui-icons#12]
In the previous icon set there were two 'handle' icons:

- `handle-horizontal`
- `handle-vertical`

![screenshot 2018-08-27 10 14 57](https://user-images.githubusercontent.com/5899/44676239-b3ea5180-aa00-11e8-8c73-8b22c16efafc.png)

In the new set, it appears these handles have been changed in favor of the `ellipsis` icon. Would it be possible to have a vertical `ellipsis` icon as well?

**Comment by johnmgriffith** [comment]
This makes sense to us. We can either create a horizontal and vertical versions, or we can keep the current "ellipsis" icon and have it centered exactly in the middle of the view box so that it can be easily rotated.

**Comment by johnmgriffith** [comment]
@jordanisip in the new release 1.1.4, the `ellipsis` icons are now perfectly aligned in the center of the viewbox, so it should be very easy in CSS to rotate the icons 90 degrees (or animate it, depending on what our patterns allow) for vertical alignment.
