### ISSUE TITLE
Slice Icon

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-ui-icons#134]
We would like to have a "Slice" icon which could be used when placing a `Slice` widget inside of an `Expand` widget in the ArcGIS JS API. This is the icon currently used in the Scene Viewer:

<img width="123" alt="Screenshot 2020-06-18 at 10 44 29" src="https://user-images.githubusercontent.com/3759114/84998877-b4615880-b150-11ea-8f0c-4d703e780213.png">

ArcGIS JS API: https://developers.arcgis.com/javascript/latest/sample-code/building-scene-layer-slice/index.html

**Comment by KatelynSeitz** [comment]
The icon above is available in Calcite UI https://esri.github.io/calcite-ui-icons/#slice

**Comment by johnmgriffith** [comment]
Yes. Like Katelyn said, we already have this icon installed:

![image](https://user-images.githubusercontent.com/30184050/85074466-6f99e980-b171-11ea-8e53-858d32430b7a.png)
