### ISSUE TITLE
Daylight Icon

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-ui-icons#136]
We would like to have a "Daylight" icon which could be used when placing a `Daylight` widget inside of an `Expand` widget in the ArcGIS JS API. This is the icon currently used in the Scene Viewer:

<img width="77" alt="Screenshot 2020-06-18 at 10 50 39" src="https://user-images.githubusercontent.com/3759114/84999622-b1b33300-b151-11ea-90c2-3795ab548093.png">

ArcGIS JS API: https://developers.arcgis.com/javascript/latest/sample-code/widgets-daylight/index.html

**Comment by KatelynSeitz** [comment]
The icon above is available in Calcite UI https://esri.github.io/calcite-ui-icons/#brightness

**Comment by johnmgriffith** [comment]
![image](https://user-images.githubusercontent.com/30184050/85074840-12526800-b172-11ea-98c6-70f36fd484a3.png)
