### ISSUE TITLE
Octagon shape

### ISSUE THREAD

**Issue by spatialdude** [Esri/calcite-ui-icons#151]
Sorry, not wanting to be too pedantic but the new "x-[hexagon](https://en.wikipedia.org/wiki/Hexagon)" is in fact an ["octagon"](https://en.wikipedia.org/wiki/Octagon)

![image](https://user-images.githubusercontent.com/7235583/92822066-18718100-f40f-11ea-99d5-2b4e1a39b850.png)

**Comment by johnmgriffith** [comment]
Haha, oh my gosh you are absolutely right
