### ISSUE TITLE
Add text underneath icons in reference page.

### ISSUE THREAD

**Issue by johnmgriffith** [Esri/calcite-ui-icons#16]
I think this could be a toggle function to display or hide text underneath the icons. Like in issue #14, the toggle could be located next to the "Filled" toggle on the header.

From this:
![image](https://user-images.githubusercontent.com/30184050/44681679-230e7880-a9f6-11e8-9c1d-bd873a7ef0bd.png)

to this:
![image](https://user-images.githubusercontent.com/30184050/44681646-0c682180-a9f6-11e8-87c4-656b7c8ec999.png)

**Comment by codylawson** [comment]
Would it also make sense to have a toggle/dropdown for icon sizes?

**Comment by paulcpederson** [comment]
@johnmgriffith Is that is better than showing the text all the time?

**Comment by johnmgriffith** [comment]
@paulcpederson I'd have to see what it looks like with text first. It might be too busy.

@codylawson As for a dropdown for icon sizes, I'm not sure it's necessary since there aren't any conceptual differences between the sizes. What would be the use case for needing to see all the 16s or 24s at once?

**Comment by codylawson** [comment]
@johnmgriffith agreed they're not conceptually different, but in practice they are different paths. I guess if the purpose of the viewer is only to help in finding the icon you need, it may not be necessary. But if its purpose is to fully document the icon set, it could be useful.

You raise a good point though, the icons aren't different in the same way `outline` and `filled` are.

**Comment by paulcpederson** [comment]
@codylawson yeah, you can still see all the sizes by opening the icon, so I don't really think we really need a sizes toggle.

**Comment by paulcpederson** [comment]
text seems to work well.
