### ISSUE TITLE
Find all icons of a certain category

### ISSUE THREAD

**Issue by johnmgriffith** [Esri/calcite-ui-icons#172]
Currently, search only looks at tags. Can we add the functionality to look at the category too?

For example, if I search "charts and graphs", I only get a handful of icons that are in that category.

![image](https://user-images.githubusercontent.com/30184050/109370558-b2aa7180-7855-11eb-8edb-1349526872db.png)

**Comment by macandcheese** [comment]
This will be in the new icon search on the Developer site!

**Comment by macandcheese** [comment]
Available https://developers.arcgis.com/calcite-design-system/icons/
