### ISSUE TITLE
Lighten up the Trashcan icon?

### ISSUE THREAD

**Issue by johnmgriffith** [Esri/calcite-ui-icons#174]
@asangma suggested that we lighten up the `trash` icon. As of now it's pretty "heavy", with a few internal vertical and horizontal lines. As a general consensus among the Online team, they'd prefer if it was lighter.

Here is what the trashcan icon looks like now
![image](https://user-images.githubusercontent.com/30184050/109696088-83d81800-7b41-11eb-97b4-45c55610dae3.png)

And here is how it looks in context with other cards in a list.
![image](https://user-images.githubusercontent.com/30184050/109696021-73c03880-7b41-11eb-9ddd-1fd3085c532c.png)

A possible proposal is this update. As a general rule, our team doesn't like having multiple weights or styles of the same icon. So if we were to propose this, it would be a _replacement_ of the current icon, _not_ an addition.

![image](https://user-images.githubusercontent.com/30184050/109696494-f812bb80-7b41-11eb-97f7-5661a919dc34.png)

![image](https://user-images.githubusercontent.com/30184050/109696706-30b29500-7b42-11eb-9da0-0b1d4708632e.png)

What are other people's perspectives?

**Comment by paulcpederson** [comment]
Very clean without the lines, I'm a fan

**Comment by sfrizzell** [comment]
I'm open to exploration. Would like to prevent the perception of a Starbucks Grande cup.

**Comment by KatelynSeitz** [comment]
Agreed! I see a few opportunities to perhaps polish this icon finding the right level of detail so it is more than an ambiguous rectangle, but not leaning too heavy. 

Did a bit of brief research to find common examples of trash can icons across social media and web app sites. I could only find one without interior detail.
![gmail](https://user-images.githubusercontent.com/29716057/109709193-159b5180-7b51-11eb-9856-ca06338b37ef.png)
![google drive](https://user-images.githubusercontent.com/29716057/109709196-1633e800-7b51-11eb-8aee-0546b043cf6b.png)
<img width="113" alt="illustrator" src="https://user-images.githubusercontent.com/29716057/109709199-16cc7e80-7b51-11eb-80b1-c3736aa3d71d.png">
![messenger](https://user-images.githubusercontent.com/29716057/109709210-18964200-7b51-11eb-9265-fc869a86c7fd.png)
<img width="254" alt="outlook" src="https://user-images.githubusercontent.com/29716057/109709213-18964200-7b51-11eb-8a21-4447771934a0.png">
<img width="221" alt="reddit" src="https://user-images.githubusercontent.com/29716057/109709215-192ed880-7b51-11eb-9dcc-a2e605cb4dfd.png">
<img width="189" alt="teams" src="https://user-images.githubusercontent.com/29716057/109709217-192ed880-7b51-11eb-877b-79afdec52017.png">
<img width="268" alt="tumblr" src="https://user-images.githubusercontent.com/29716057/109709218-19c76f00-7b51-11eb-8388-b351b7deba87.png">
<img width="188" alt="twitter" src="https://user-images.githubusercontent.com/29716057/109709220-19c76f00-7b51-11eb-8d7d-367a57b01774.png">

**Comment by KatelynSeitz** [comment]
Moral of the story, I think we can move forward with a few iterations and get this icon updated in our next upcoming release. This might look like dropping down to two interior lines instead of three, refining the overall shape, exaggerating the handle a bit more in lieu of interior detail that becomes too dense, etc.

**Comment by KatelynSeitz** [comment]
Also curious about patterns where we use the `trash` for remove versus `minus-circle` for remove. A contributing factor to why the trash icon feels perhaps more noticeably heavy in the provided example is because it is repeated on every card where as in the example below we simply use minus. Maybe that icon only makes sense in tandem with the plus-circle? 
Either way, I agree the trash icon can use some lightening up, but curious about the overall pattern, too! 👀😊
<img width="372" alt="list view" src="https://user-images.githubusercontent.com/29716057/109710679-d2da7900-7b52-11eb-8c32-4d87531b3d43.png">

**Comment by macandcheese** [comment]
I would expect `minus-circle` to be a less severe action - just removing an item from view, where `trash` is for the destructive  "delete" or remove completely.

**Comment by KatelynSeitz** [comment]
Hi y'all! Let's move forward with getting this icon updated. You can look for the PR coming soon and comment if you have questions. We revisited this design to make the following improvements:

> a. match the general level of detail in the rest of our set and surrounding icons
> b. keep the legibility of the icon to read specifically as a trash can
> c. remove the detail that was becoming redundant or unnecessarily tight 
> d. now that there is no center 1px line, the icon can be horizontally centered
 
<img width="153" alt="before and after" src="https://user-images.githubusercontent.com/29716057/110541144-3711b580-80dc-11eb-9db4-7210634202ff.png">

before:
![image](https://user-images.githubusercontent.com/29716057/110541642-e3539c00-80dc-11eb-88da-1a344f945cd1.png)

after:
<img width="1622" alt="mock up" src="https://user-images.githubusercontent.com/29716057/110541152-3842e280-80dc-11eb-84b7-458b773deeec.png">

**Comment by sfrizzell** [comment]
This is a good update for the trash can icon. Let's make the change. Thanks Alan for bringing up the consideration, Griff for starting the conversation here, and Katelyn for refining the design.

**Comment by KatelynSeitz** [comment]
This is issue was resolved in release #177
