### ISSUE TITLE
Type Error on `CalciteMultiPathEntry`

### ISSUE THREAD

**Issue by lggorman** [Esri/calcite-ui-icons#180]
Should the icons exported with the type `CalciteMultiPathEntry` be exported with a type of `CalciteMultiPathEntry[]` instead? When I log out one of the multi path icons, for example `colorCodedMap24` it appears to be an array even though it is typed as an object. 

Ideally we'd like to be able to use the type `CalciteIconPath`, which includes the array version of the type.

Thanks!

**Comment by johnmgriffith** [comment]
@paulcpederson, would you be able to look at this issue?

**Comment by paulcpederson** [comment]
@lggorman should be in the next release when that is published (not sure when that's planned)
