### ISSUE TITLE
bullet list item icon

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-ui-icons#191]
We need a bullet (circle) icon for list items in the dropdown and other components in the calcite-component library. 

More details here:
https://github.com/Esri/calcite-components/issues/957

**Comment by paulcpederson** [comment]
My request: please center this icon in the art board.

**Comment by KatelynSeitz** [comment]
Will do. And I am guessing using this example for scale? 
![image](https://user-images.githubusercontent.com/29716057/124842636-ed7b8f00-df44-11eb-8c83-4f26b559e5ee.png)

**Comment by julio8a** [comment]
Per design, icon should be 4x4px

PR: https://github.com/Esri/calcite-components/pull/2485

**Comment by julio8a** [comment]
any updates on this one?

**Comment by KatelynSeitz** [comment]
Yup. Working on that branch right now. Will be included in the latest release by the end of the day. 👍🏽

**Comment by KatelynSeitz** [comment]
resolved in v3.16.6
