### ISSUE TITLE
Remove unused metadata from keywords.json

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-ui-icons#196]
There is some unused metadata in `keywords.json` for icons that no longer exist:

<img width="499" alt="Screen Shot 2021-08-10 at 2 46 24 PM" src="https://user-images.githubusercontent.com/4733155/128940213-a1629568-3be9-47ef-a94b-a8812162fecd.png">

**Comment by KatelynSeitz** [comment]
Found two that needed to remain:
pin-tear-f
pop-up-blank-f

All other items have been removed in my 3.16.8 branch. Will merge soon.

**Comment by macandcheese** [comment]
This is resolved, closing.
