### ISSUE TITLE
Metadata Cleanup for Recently Added Icons

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-ui-icons#209]
The latest version/s introduced some metadata discrepancies - nitpick alert 🚨 : 

"convert", "language", "language-translate", and "touch" are using `generic` instead of `Generic`.

"terminal" is using `window` instead of `Windows`.

`partly-cloud` seems like it should be named `party-cloudy` to match `cloudy`.

Additionally - maybe preference here - it would be nice to group those 12 new icons into a new `Weather` category 🌥️ 🌦️

**Comment by KatelynSeitz** [comment]
Good stuff! Thanks for the close look at these. Updates have been merged into master.

**Comment by macandcheese** [comment]
Thanks @KatelynSeitz !
