### ISSUE TITLE
Doc UI enhancement: ability to filter by version of calcite-ui-icon and version of calcite-components

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-ui-icons#213]
Please add the ability to filter icons by the version of calcite-ui-icon and version of calcite-components.  When working with the icons via calcite-components it becomes cumbersome and unproductive to look at each icon and then track down if its supported in the version of calcite-components I'm using in a particular application.

https://developers.arcgis.com/calcite-design-system/icons/

**Comment by macandcheese** [comment]
@jgrayson-apl I've added an issue to track this on the Developer site (https://github.com/ArcGIS/afd-calcite-documentation/issues/268) - as this will apply to and benefit all the icon libraries shown there.

**Comment by macandcheese** [comment]
Since this is a docs site enhancement and not specific to Calcite UI - I'm going to close this and use the above issue to track.
