### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by bradp** [Esri/calcite-ui-icons#214]
According to `LICENSE.md`, this project is licensed under the Esri Master License Agreement , which reads to me as not 100% applicable to icons and art assets. I see other Esri projects licensed under MIT or Apache, which matches what most icon repos seem to use, along with Creative Commons.

Just wanted to see if anyone could provide clarification before I use these. 

Thanks!

**Comment by KatelynSeitz** [comment]
@macandcheese

**Comment by juliepowell** [comment]
@bradp all Calcite assets including the icons are licensed under Esri's MLA.

**Comment by bradp** [comment]
Appreciate the response! 

I'm a bit curious how those terms specifically apply to this project. 

I'm not a lawyer, but according to section 2.1, I'd fall under an "Anonymous Users", as I don't provide a Named User Credential. This, along with 2.5b means that I'm only licensed to use this project within an Esri/Esri-partner project. 

I may be reading it wrong, but it seems to me that even if accreditation and notices, my usage of these icons in anyway would not be allowed unless I were to have a prior engagement with Esri?

There are [other projects](https://www.esri.com/content/dam/esrisites/en-us/media/legal/product-specific-terms-of-use/e300.pdf) with specific terms of use/dual licensed to allow for use, is there a chance for this project to be dual licensed under a more permissive license that would allow for its use?

As I said, I'm not a lawyer, so feel free to re-close if there isn't anymore clarification you can give, appreciate the help!
