### ISSUE TITLE
Naming inconsistencies. 

### ISSUE THREAD

**Issue by sterlingwalsh** [Esri/calcite-ui-icons#217]
On 3.18.2

As per the docs `If the icon is a filled alternate, it will have F at the end of the variable name.`

This is the case for all but pinTear and popUpBlank which have the dimension number after the F as opposed to before and have file names, for instance pinTearF24.

**Comment by KatelynSeitz** [comment]
Thanks, @sterlingwalsh. You are correct- will resolved in the next upcoming release!

**Comment by KatelynSeitz** [comment]
Resolved on 3.18.3 release ✅
