### ISSUE TITLE
Calculator Icon

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#22]
Hey there.
We are currently using a calculator icon in places.
Would it make sense to add this concept to the library?

![image](https://user-images.githubusercontent.com/12503298/44868314-5263f600-ac3f-11e8-85fd-f9300ffdecc0.png)

![image](https://user-images.githubusercontent.com/12503298/44868282-3bbd9f00-ac3f-11e8-9d47-8170b67f676e.png)

**Comment by KatelynSeitz** [comment]
Yup, we have a handful of icons in our color set that use a calculator and we do not yet have anything in Clacite-UI-icons for various calculate functions. Let's add it.

**Comment by johnmgriffith** [comment]
I noticed that your `sort-ascending`, `sort-descending` and `show detailed view` icons aren't ours. Do you know know where you got those from? Is there something wrong with the ones we have currently?

**Comment by asangma** [comment]
> Do you know know where you got those from?

Not sure. I assumed they came from the Icon Team. I recall having a long discussion moons ago about whether the lines should change with the arrows. #oldtimes

**Comment by johnmgriffith** [comment]
@asangma, would you mind putting in a Workfront request for this new icon? Thanks

**Comment by asangma** [comment]
Roger that.

**Comment by johnmgriffith** [comment]
This issue is resolved in the latest release, v1.3.0
