### ISSUE TITLE
`handle-vertical` missing release version

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-ui-icons#222]
Checking in for another nitpicky content issue - `handle-vertical` is missing a "release" tag / version: 
<img width="305" alt="Screen Shot 2022-03-10 at 2 34 13 PM" src="https://user-images.githubusercontent.com/4733155/157766309-c07f1409-5aea-48f2-ac79-5f44bbf77366.png">

**Comment by KatelynSeitz** [comment]
Thanks, Adam, for catching these. Will be addressed in the next release coming soon.

**Comment by KatelynSeitz** [comment]
Resolved in release #223
