### ISSUE TITLE
How to use compass icons?

### ISSUE THREAD

**Issue by johnmgriffith** [Esri/calcite-ui-icons#23]
With the new addition of `compass-needle`, it's becoming a little more vague how and when we should use the different `compass` icons.

List is as follows:
• compass
• compass-needle
• compass-north
• compass-north-circle

![image](https://user-images.githubusercontent.com/30184050/44869415-62c9a000-ac42-11e8-84a9-71ae8a144772.png)
![image](https://user-images.githubusercontent.com/30184050/44869435-6fe68f00-ac42-11e8-925f-939dbe2092c9.png)

My suggestion is that these icons: ![image](https://user-images.githubusercontent.com/30184050/44869772-4712c980-ac43-11e8-8e57-fbf03f1fc335.png) are better for when indicating current location or direction facing.
The `north` ![image](https://user-images.githubusercontent.com/30184050/44869859-76c1d180-ac43-11e8-94fa-5b8d4e2b1cbd.png) and `needle` ![image](https://user-images.githubusercontent.com/30184050/44869894-88a37480-ac43-11e8-860a-ca85771b50da.png) icons are better for indicating orientation of the map. But the real question is when and how to use these? Feel free to share your thoughts.

**Quick note about rotating:**
Some of these assets are better for rotating than others. `compass` and `compass-needle` align perfectly in the center of the artboard, so they can be easily rotated. But the `compass-north…` icons are slightly off center so that the point of the compass can land perfectly on a sharp pixel.

**Comment by johnmgriffith** [comment]
Creative Lab internal discussion at the slack channel `cuii-issue-23`

**Comment by julio8a** [comment]
Closing this out. Re-open if you feel there is more discussion needed on this topic.
