### ISSUE TITLE
Additional Satellite icons needed

### ISSUE THREAD

**Issue by TheBlueDog** [Esri/calcite-ui-icons#24]
Its going to be easier on our developers if we have several versions of this versus trying to manipulate it through CSS.

The current icon would still be used, but ones with only two signal bars, one signal bar, and no signal bars are needed. See example below.

![screen shot 2018-09-10 at 1 06 50 pm](https://user-images.githubusercontent.com/5419306/45312563-6e4a8000-b4fa-11e8-841f-07b2ceca03eb.png)

**Comment by johnmgriffith** [comment]
Do we use Calcite UI icons as both tools and status icons?

**Comment by johnmgriffith** [comment]
This issue is resolved in the latest release, 1.3.0
