### ISSUE TITLE
bookmark (filled) icon name does not follow existing convention

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-ui-icons#251]
This came up in https://github.com/Esri/calcite-components/issues/6272#issuecomment-1404185442:

> 1. `bookmark-f` – the convention for filled icons has been [`<iconName>-<size>(-f)`](https://github.com/Esri/calcite-ui-icons/commit/87423ee157e9107990c34e839caeceb86197d534), but for this one [it's `<iconName>(-f)-<size>`](https://github.com/Esri/calcite-ui-icons/commit/1aef262233f162c0b294d34d21effcc23a5719a4). This is causing the utility to not build the correct file name.

Not sure if this issue applies to other icons as well.

cc @SkyeSeitz

**Comment by SkyeSeitz** [comment]
Resolved in release [v3.21.0 ](https://github.com/Esri/calcite-ui-icons/releases/tag/v3.21.0).
