### ISSUE TITLE
Missing icons in JS files output

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-ui-icons#252]
This came up in https://github.com/Esri/calcite-components/issues/6272#issuecomment-1404185442

> 2. `1-2x`, `8x`, `1-4x`, and similar ones – these have no matching data path files ([SVGs start with 1-2x](https://github.com/Esri/calcite-ui-icons/tree/master/icons), [JSON starts with aZ16](https://github.com/Esri/calcite-ui-icons/tree/master/js)).

cc @SkyeSeitz

**Comment by SkyeSeitz** [comment]
Thanks, @jcfranco. I see the js output gives svgs titled first with integer an `i` prefix so there are data paths to the icons mentioned but they are listed as: 
```
i12x16.js
i14x16.js
i18x16.js
i1X16.js
```
etc.

Do you recommend any changes to the metadata or svg names for this issue or can we re-route these as is?

**Comment by jcfranco** [comment]
Oh, I forgot that icons that start w/ numbers get prefixed. 😅 This is a non-issue for the icons then as the icons you listed above are available (e.g., [`i12x16.js`](https://unpkg.com/browse/@esri/calcite-ui-icons@3.20.7/js/i12X16.js)). The icon utility in calcite-components needs to be updated to handle the `#-#x`/`#x` cases. 

Thanks for looking into this!
