### ISSUE TITLE
Display version number for when the icon was released

### ISSUE THREAD

**Issue by codylawson** [Esri/calcite-ui-icons#31]
It would be nice to see what version an icon was released on in the icon browser app. FontAwesome does something similar:

![screen shot 2018-11-06 at 3 16 28 pm](https://user-images.githubusercontent.com/5149922/48097528-61cf6480-e1d7-11e8-9bbb-790593a00ac8.png)

**Comment by paulcpederson** [comment]
This idea is 💯

**Comment by julio8a** [comment]
Awesome idea!

**Comment by macandcheese** [comment]
https://github.com/Esri/calcite-ui-icons/pull/33
