### ISSUE TITLE
Direction Mode (absolute/bearing - relative/deflection) Icons

### ISSUE THREAD

**Issue by hcampos-professional** [Esri/calcite-ui-icons#312]
Within ArcGIS Pro there is a concept called "on-screen constraints:" https://pro.arcgis.com/en/pro-app/latest/help/editing/enable-dynamic-constraints.htm. It allows users to constrain the segment of a line or polygon to be along a specific direction/bearing. The direction can be either "Absolute" (relative to north or the main axis of the spatial reference) or relative to the previous segment, in which case it's called "Deflection."

Within the context of the ArcGIS Maps SDK for JavaScript, we are considering a similar system and would like to have icons representing the 2 direction modes: absolute and deflection.

Here is a quick mockup we did for the two icons, based on the current [rotate](https://developers.arcgis.com/calcite-design-system/icons/?icon=rotate&library=Calcite%20UI&query=rotate), [compass-needle](https://developers.arcgis.com/calcite-design-system/icons/?icon=compass-needle&library=Calcite%20UI&query=compass) and [line-straight](https://developers.arcgis.com/calcite-design-system/icons/?icon=line-straight&library=Calcite%20UI&query=line)

![image](https://github.com/Esri/calcite-ui-icons/assets/136828178/360844e4-217a-4237-b165-0343b1978d64)

We intend on using these icons inside of a `<calcite-button>` as well as a `<calcite-dropdown>`.

**Comment by allieorth** [comment]
These icons were created and released in [v3.25.3](https://github.com/Esri/calcite-ui-icons/releases/tag/v3.25.3)
