### ISSUE TITLE
Elevation Mode Icons

### ISSUE THREAD

**Issue by hcampos-professional** [Esri/calcite-ui-icons#313]
In the ArcGIS Maps SDK for JavaScript we have the concept of an "Elevation Mode" which can be `absolute-height`, `relative-to-ground`, `relative-to-scene` or `on-the-ground`. It indicates how geometry coordinates are to be interpreted and displayed in a 3D view. When allowing users to specify elevation values, we permit values in those modes, except for `on-the-ground` because elevation values are always zero in that mode.

See this sample for more details: https://developers.arcgis.com/javascript/latest/sample-code/scene-elevationinfo/

We would like to have icons for the available elevation modes, in particular for the ones for which users can specify numerical values: `relative-to-scene`, `relative-to-ground` and `absolute-height`.

Here is a quick mockup we did based on existing icons like [altitude](https://developers.arcgis.com/calcite-design-system/icons/?icon=altitude&library=Calcite%20UI&query=elevation):

![image](https://github.com/Esri/calcite-ui-icons/assets/136828178/52b9da55-c019-4904-9f11-339fa4fc0ea9)

We intend on using these icons inside of a `<calcite-button>` and `<calcite-dropdown>` to allow users to select their preferred elevation mode.

**Comment by dmartini-zrh** [comment]
Here is a mockup including `on-the-ground`:

![Elevation mode icons](https://github.com/Esri/calcite-ui-icons/assets/113533121/1440a45b-81d8-41f3-9c23-4e688228a365)

Having icons for all 4 Elevation Mode options would make them usable in Scene Viewer as well – we currently have a text-only dropdown, but we are considering something more informative.

**Comment by hcampos-professional** [comment]
@allieorth is there some document somewhere explaining what the process/requirements for Calcite are? For example, the document linked from workfront mentions various sizes, but which ones are needed for Calcite icons?

Other than that, going forward, are there plans to integrate Workfront with Github? Should we create requests directly in workfront or create them first here in the Calcite repo?

**Comment by allieorth** [comment]
Hey @hcampos-professional,
The calcite documentation is going to be in the ReadMe [here](https://github.com/Esri/calcite-ui-icons#readme) in the Github repo. It says the sizes there, but we build Calcite icons at three sizes: 32, 24, and 16 pixels.

I don't believe there is any plan in the works to integrate Workfront with Github, the best way to request an icon is through Workfront. Our team monitors the issues here, but jobs are assigned through Workfront so any icon requests here in the calcite repo will be redirected there.

**Comment by allieorth** [comment]
These icons were created and released in [v3.25.3](https://github.com/Esri/calcite-ui-icons/releases/tag/v3.25.3)
