### ISSUE TITLE
Metadata issue for `dimensions-unit`

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-ui-icons#316]
The `dimensions-unit` "release" metadata has a trailing period: https://github.com/Esri/calcite-ui-icons/blob/7d1deb5518b5ac3f15121294eb17e86d33d079a2/docs/keywords.json#L13304C16-L13304C23

This was throwing an error in the developer site icon search, which we are handling now, but others expecting a valid semVer value might run into errors.

**Comment by nicklu10** [comment]
fixed, thanks for spotting the mistake!
