### ISSUE TITLE
Caret-left and caret-right are don't have the same baseline (1.5.0)

### ISSUE THREAD

**Issue by ffaubry** [Esri/calcite-ui-icons#32]
![image](https://user-images.githubusercontent.com/3506166/49163704-8dc79c80-f2e2-11e8-9478-6b40e0f2ead0.png)

It seems that caret-left was simply a rotation of caret-right.
Since caret-right was not centered they are now misaligned.

**Comment by johnmgriffith** [comment]
I just reviewed those files, and they look fine to me. Caret-left and caret-right are reflections of each other.

Can you specify exactly which icon files you are seeing this issue? According to our files, it doesn't look like it's affecting the outlined versions.

**Comment by ffaubry** [comment]
@johnmgriffith My apology. I have been deceived by my own eyes.
I did some further investigations and found that things are aligned!

![image](https://user-images.githubusercontent.com/3506166/50191497-01a60500-02e3-11e9-83b5-d0912df358b8.png)

And

![image](https://user-images.githubusercontent.com/3506166/50191513-11254e00-02e3-11e9-94c4-5da6542d3598.png)

Thanks for looking into it.

I'm closing this issue.
