### ISSUE TITLE
Icon Request - Clipboard Check

### ISSUE THREAD

**Issue by codylawson** [Esri/calcite-ui-icons#36]
There's currently a copy-to-clipboard icon available, but it would help to also have a "copied-to-clipboard" or "clipboard-check" icon to show the success state of having copied something.

A couple examples of copy components that would be improved with this icon:
https://calcite-react.netlify.com/copy-to-clipboard
![screen shot 2019-01-04 at 11 15 49 am](https://user-images.githubusercontent.com/5149922/50703698-379cf600-1012-11e9-9e45-fb7479ee270c.png)
![screen shot 2019-01-04 at 11 15 56 am](https://user-images.githubusercontent.com/5149922/50703700-3966b980-1012-11e9-8956-1014f687ea3a.png)

https://developers.arcgis.com/dashboard
![screen shot 2019-01-04 at 11 16 21 am](https://user-images.githubusercontent.com/5149922/50703710-3ec40400-1012-11e9-90c4-f217211c3d11.png)
![screen shot 2019-01-04 at 11 16 27 am](https://user-images.githubusercontent.com/5149922/50703713-408dc780-1012-11e9-92c2-589d34f74c26.png)

Thinking along these lines:
![screen shot 2019-01-04 at 11 28 29 am](https://user-images.githubusercontent.com/5149922/50704248-f7d70e00-1013-11e9-80c7-e2fec8ec26ea.png)

Let me know if there's a better place to make icon requests or if this is already planned...

**Comment by johnmgriffith** [comment]
We think that the checkmark is actually a better option than a new icon, since the icon is already so small, and the modifier change will probably not be very noticeable. A simple checkmark conveys the idea very effectively, and is a better clue to the user that an action has happened.

**Comment by asangma** [comment]
Don't mean to sniper, but as we are also working generally on app messaging for things like error/success/processing and that kind of thing, I would agree that a simple checkmark would be a good approach.

This would align with success moments elsewhere in any given app...and would not require acute representations of "success".

**Comment by codylawson** [comment]
I suppose that's fair, having a noticeable change for the icon is valuable. A 16px clipboard-check may make that too hard to see. @johnmgriffith You've convinced me 😄

**Comment by codylawson** [comment]
Closing, as the icon seems unnecessary given this discussion.
