### ISSUE TITLE
Icon request - Analysis icon

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#37]

**Comment by asangma** [comment]
## Concept
General GIS analysis performed on a layer.

## Current icon
![analysis-16](https://user-images.githubusercontent.com/12503298/50705243-0242d900-100f-11e9-9212-0fce4f5b9dd1.png)
Currently found in the toc_icons2.png sprite used in the map viewer.

![analysis-16-in-situ](https://user-images.githubusercontent.com/12503298/50705344-649bd980-100f-11e9-81f5-9ff36492265e.png)

**Comment by asangma** [comment]
Would be good to have a monochrome version of this in all sizes that the icon repo does, filled and "normal".

**Comment by KatelynSeitz** [comment]
@asangma, can you show the use-case(s) as well?

**Comment by asangma** [comment]
Would like to explore a general "analysis" concept. This icon seems to be a specific analysis icon.

**Comment by asangma** [comment]
### Use case 1
User wants to run an analysis using a particular layer in map viewer. User would click the analysis button and open a list of analysis tools.

### Use case 2
User wants to view all the available analysis tools (no layer selected).

**Comment by asangma** [comment]
Also, the screen above shows the icon in its current usage. I will email you other examples.

**Comment by KatelynSeitz** [comment]
Thanks!

**Comment by asangma** [comment]
Hi @KatelynSeitz! Any updates? :)

**Comment by KatelynSeitz** [comment]
Hey @asangma, sorry for the delay on this. Let's get a request open for this in Workfront since it is a new concept.

**Comment by asangma** [comment]
Cool.

**Comment by johnmgriffith** [comment]
Closing this issue
