### ISSUE TITLE
Icon request: destructive icon

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-ui-icons#39]
For Calcite, we're working on a messaging pattern, which involves icons.

Messaging:
- Information: circle with `i` (blue)
- Success: checkmark (green)
- Warning: a triangle with `!` (yellow or orange (still needs work)) 
- Destructive: stop sign with `!` (red) 

We have icons for Information, success, and warning.
However, we don't have the stop sign with `!`, based on our concept for messaging.

**Request:** We need a destructive icon (stop sign with `!`)

**Comment by paulcpederson** [comment]
@julio8a I think `exclamation-mark-circle` is what we currently use, would be replace that, or just add a new one? It's tagged as `symbols` `invalid` `error` `broken`

**Comment by julio8a** [comment]
@paulcpederson, 

I'm thinking we'll replace to follow the pattern above. However, teams are not tied to always using the icon as it'll be an opt-in, but we should follow the pattern for consistency across the platform.

From a discussion with Mitch and Tao, they are good with this change to create more distinction and separation between warning and destructive (aside from color, as the shape is more noticeable). Also, the circle with `!` (destructive) and circle with `i` (information) are very close from a form standpoint and have trouble with accessibility in delivering the message.

Some of the concerns with the `stop` sign shape are aesthetics, which I'm hopeful the icon team can help to make it look not "old" and as Mitch said, "ugly".

**Comment by johnmgriffith** [comment]
This makes sense to me. Let's put this into an official Workfront request, and we'll build it for you.

**Comment by julio8a** [comment]
@johnmgriffith, Workfront request was created first and I added a link to this issue.

**Comment by KatelynSeitz** [comment]
Got the WF request 👍 Will post concept soon

**Comment by johnmgriffith** [comment]
This Workfront task was cancelled by @julio8a , so we're going to close this issue as well.
