### ISSUE TITLE
Collections - 24px icon alignment

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#43]
![image](https://user-images.githubusercontent.com/12503298/53924285-634b5500-4030-11e9-9c96-50e926c6cf7e.png)

Would it be optically problematic to have the upper right part of `collection-24.svg` at the same place as it is in `collection-24-f.svg`?
![image](https://user-images.githubusercontent.com/12503298/53924350-9988d480-4030-11e9-8e69-f0497e833b40.png)

**Comment by asangma** [comment]
@paulcpederson @KatelynSeitz @johnmgriffith 

Looks like I'm no longer able to assign issues. 
(゜-゜)

**Comment by KatelynSeitz** [comment]
Good catch. Let's adjust the 24 outlined to match the filled.

Not sure why you can't assign issues at the moment...🤔🤔🤔 
Can I still close out an issue if I'm not assigned to it? 

If so, we will include this change in the next release and close out the issue then.

**Comment by asangma** [comment]
Thanks @KatelynSeitz .
I'm still able to close issues.

**Comment by asangma** [comment]
Sorry I didn't notice this before (I've only been working with 16 and 24 icons), but `collection-32.svg` might also need a review. Let me know if you'd like an issue for that or if the difference between the outlined and filled on that icon is needed for optical reasons.

**Comment by asangma** [comment]
![collection-32](https://user-images.githubusercontent.com/12503298/53968386-cb8b4c80-40ab-11e9-8a03-776b70003e40.gif)

**Comment by johnmgriffith** [comment]
Thanks for pointing that out. I'll update 1.6.4 with the new `collection-32` icon too

**Comment by johnmgriffith** [comment]
Both of these icons were resolved in release v1.6.4, and are now merged to master. Closing this issue.

**Comment by asangma** [comment]
Thanks @johnmgriffith!
