### ISSUE TITLE
Popup "designer" or "styler"

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#45]
We currently have the "configure popup" icon.
![image](https://user-images.githubusercontent.com/12503298/53974614-c92eef80-40b7-11e9-8423-1bbbedf1bcf2.png)

This is a good one and has a technical feel befitting the current and legacy ways of exposing this to the user. 

Our future map authoring app will have an experience that is more like "popup design", "popup style", or "popup layout".

Would we be able to make a similar icon to "configure" that is less technical and more about "styling" or "designing" a popup?

Thanks!

cc @johnmgriffith @KatelynSeitz

**Comment by KatelynSeitz** [comment]
Cool. So there is still a need for the existing `configure-popup` icon as is, but in addition, there is a need for a `style-popup`/ `design-popup` as well? 

We can probably leverage the styling/design pallet to some degree (_rough_ sketch below). Sounds like we can get a request open for a new icon and go from there. 
![image](https://user-images.githubusercontent.com/29716057/53979861-b3272c00-40c3-11e9-8253-8561611f6574.png)

**Comment by asangma** [comment]
I think the configure may eventually be replaced by "design", but for now we would want to keep both.

I think we may want to update the popup portion of the icon too and simplify it. Partly because the popups on web apps tend to stack content vertically (and not so much like a mini webpage).

Here's an example:
![popup eg](https://user-images.githubusercontent.com/12503298/54044142-0dd38d00-4183-11e9-85d0-b444f732db66.gif)

re: palette / brush
It would be good to explore something closer to "design" and further from "art". Maybe that's like a right-angle square, ruler, or that sort of concept.

:)

**Comment by KatelynSeitz** [comment]
Gotcha. Let's address all three popup icons in the request then:
`popup.svg`
`configure-popup.svg`
`design-popup.svg`

A simplification that is still future UI proof would be good. 👍🏽

**Comment by asangma** [comment]
Sweet!

**Comment by asangma** [comment]
Let this fall off. Sorry.
Request submitted.

**Comment by KatelynSeitz** [comment]
resolved in v1.6.6
