### ISSUE TITLE
Request for a Grab Icon (hand) that matches to the CSS cursor: grab

### ISSUE THREAD

**Issue by sethisameer** [Esri/calcite-ui-icons#47]
We've a requirement in our project to use Grab icon while performing Pan action in UI. I could locate 'Move' icon and 2dExplore but that is not what we want to use while panning.

Request is to have an icon should be similar to the one that can be seen in CSS `cursor:  grab;`

![grab](https://user-images.githubusercontent.com/4491409/54396573-bc3e6d00-4670-11e9-87f7-fa63c9e07b32.png)

**Comment by asangma** [comment]
![image](https://user-images.githubusercontent.com/12503298/54399341-29570000-467b-11e9-92a4-9509b7814c68.png)

Is it a similar functionality to panning in Scene Viewer?

**Comment by sethisameer** [comment]
@asangma - The functionality is somewhat similar to pan the element nodes on the canvas. Its not a map, but collection of nodes on a canvas.
We're using the above icon that you referred to "Move" elements. Moving elements and panning on canvas are different actions,  so for that purpose I was looking to use the 'Grab' that closely resembles to the pan action.

**Comment by asangma** [comment]
@sethisameer Got it.
That make sense.
We do already use "pan" for manipulating maps and scenes. And TBH, we maybe should have used the hand metaphor. But seems like your experience is separate from the geographic experience and closer to a graphics experience.

![pan-move-2](https://user-images.githubusercontent.com/12503298/54547513-1a19d000-4963-11e9-8bf6-87037c1d1040.gif)


My only concern is that we will want to make sure that we name the hand icon in a way that doesn't conflict with the "pan" concept on maps...or something.

**Comment by asangma** [comment]
@janett-baresel Would you mind chiming in because I know that you're rethinking scene manipulation modes.

**Comment by sethisameer** [comment]
@asangma - Thanks for your review and considering the request. That is exactly we're doing. So when you're moving the node elements, I would keep the 'Move' icon and when I'm panning on the canvas I would prefer hand icon. Its as your teams discretion to name the icon appropriately. Only thing I need is an icon with hand!!

**Comment by asangma** [comment]
@sethisameer No worries. I don't mean to hold up the project. It'll be @KatelynSeitz or @johnmgriffith who'll take on making the icon.

It is just good to make sure that we have some kind of platform consistency in regards to what icons we use so that end users are oriented and not having to learn new icon systems with each product.

**Comment by johnmgriffith** [comment]
@asangma Do you know if any web apps are currently using icons from the Calcite UI library as cursors?

**Comment by KatelynSeitz** [comment]
Would this request be simply a **tool** icon to activate a cursor? 
or the assets for the cursor itself, so both **pan** and **drag**? 
ArcGIS Pro assets below as an example:

**Tool to activate cursor:**

`PanTool16.png` ![PanTool_B_16](https://user-images.githubusercontent.com/29716057/54553437-7125a200-496f-11e9-8ede-39c2f018f04e.png)
`PanTool32.png` ![PanTool_B_32](https://user-images.githubusercontent.com/29716057/54553438-7125a200-496f-11e9-9056-1773dee115e8.png)

____

**Pan and Drag cursor:**
`Pan32.png` ![Pan32](https://user-images.githubusercontent.com/29716057/54553751-2193a600-4970-11e9-94d5-bcfb63f2e6f4.png)
`PanDrag32.png` ![PanDrag32](https://user-images.githubusercontent.com/29716057/54553759-26f0f080-4970-11e9-9692-56a36101a597.png)

**Comment by asangma** [comment]
@sethisameer Sounds like you wanted an icon to activate a pan tool, yeah? Do you also need an asset for the cursor states or will you be using

```css
cursor: grab;
cursor: grabbing;
```

**Comment by sethisameer** [comment]
@asangma - We could make use of both the icons if they're provided. But priority is `cursor: grab`

**Comment by sethisameer** [comment]
@asangma  @KatelynSeitz  @johnmgriffith - Just thought to follow up and see if this icon is available or can be done in coming days. If it need some other request process then kindly advise.

**Comment by KatelynSeitz** [comment]
Yes, you can submit an icon request in [Workfront](https://esri.my.workfront.com) 
Feel free to reach out if you have any questions regarding the request form or process.

**Comment by sethisameer** [comment]
@KatelynSeitz thanks for suggesting, I've added a request at Workfront.
