### ISSUE TITLE
update magnifying-glass to remove the handle detail

### ISSUE THREAD

**Issue by bstifle** [Esri/calcite-ui-icons#5]
@johnmgriffith @julio8a 

Hey guys,

It would be nice to get that chunky handle removed off of magnifying-glass.

Currently on esri.com global nav we are using the icon font style that is simplified. 

There's a few other designers that think that detail is unnecessary, can we make it happen?

![comparison](https://user-images.githubusercontent.com/14083530/44123266-4e4a65be-9fdc-11e8-91de-a5e3cc000fe9.png)

**Comment by asangma** [comment]
Haw! We were just talking about the "wooden" handle.

+1 for removing it.

**Comment by johnmgriffith** [comment]
We were concerned that the icon would look too simple when compared to the icons in the rest of the set. Calcite UI is heavily based on ArcGIS Pro and Online color icon set. Here's what our magnifying glass looks like in color:

![image](https://user-images.githubusercontent.com/30184050/44160137-489e9800-a06e-11e8-9761-ac713d1e30f3.png)

Also, it's common in our Calcite UI icon set for us to add just a touch of detail, so the "wooden" handle was meant to give it that extra bit of realism. This treatment occurs in some of our icons like the lightbulb, where we use a detailed filament and ridged screw contact, or the label, where we draw a short string going through a punched-in hole.

![image](https://user-images.githubusercontent.com/30184050/44161013-fad75f00-a070-11e8-8760-569874717431.png)


I could see us reducing the detail in the magnifying glass icon, especially if it is often seen in isolation. But I believe our team is still concerned that we shouldn't deviate too far from our color icon style or become too simple. What do you think?

**Comment by mitc7862** [comment]
I think its fine to have a version of the magnifying glass that has a handle, but when it's in a search field it looks _very_ weird. It would be great to have an official version simplified for that context.

**Comment by bstifle** [comment]
yeah let's just get a new one then.

proposing the name `sans-handle-search'

**Comment by johnmgriffith** [comment]
Okay, I'm fine with this approach. Just to confirm, we're not _replacing_ the original magnifying glass, just offering a simpler version for search contexts. I think I'd type "simple" before I'd type "sans", so instead of **sans-handle-search**, and the paradigm of naming the object first, and the adjective after, I'd suggest **magnifying-glass-simple**. We can of course tag it with "sans handle" and "search" so it's still easy to find.

This is one of those weird cases where an icon needs to be created, but there isn't officially a Workfront request associated with the product. @bstifle are you willing to submit the Workfront request, and be our official requestor for it, so we can track the progress and make sure it's on our radar?

**Comment by paulcpederson** [comment]
just `search.svg` would make more sense as a name, IMO

**Comment by KatelynSeitz** [comment]
@paulcpederson , for sure.  If the magnifying glass was only used for the `search` tool (similarly to the floppy disk only being used for `save`) then, `search.svg` would make the most sense. However, various products use `magnifying-glass.svg` for zoom tools and such. For consistency, the naming convention we set up for this repo tries to stay straightforward, while the use of tags in the reference page gives us the ability to add all those other keywords.

**Comment by mitc7862** [comment]
I think the handle has a place, perhaps as an icon for an analysis tool or something, or a larger non-actionable illustration (I'm thinking empty states), but not in a search field. 

Making the magnifying glass's handle black doesn't really solve the problem we are posing. Those screenshots basically show what we have, not what we want. Also, I don't think that simplifying the icon makes it too trendy, it just makes it more simple, which is something we should strive for across our apps and calcite generally.

**Comment by mitc7862** [comment]
Perhaps the simple search icon could be filed under 'generic' or 'symbols' while the detailed magnifying glass icon could be filed under 'objects'.

**Comment by asangma** [comment]
> However, various products use magnifying-glass.svg for zoom tools and such.

Doesn't the Zoom tool have a plus inside it?

**Comment by paulcpederson** [comment]
affirmative, both plus and minus options are provided:

![screen shot 2018-08-16 at 8 43 39 am](https://user-images.githubusercontent.com/1031758/44219315-91b72080-a130-11e8-8b25-26af4aafb02e.png)

**Comment by bstifle** [comment]
ohhhh, let's change all three of those to `sans-handle`

**Comment by johnmgriffith** [comment]
The magnifying-glass icon is unchanged, but we have added a new icon called `search` in release 1.1.3. The `search` icon should be reserved for search functions only (i.e. locate, find, filter, search, etc.), while the `magnifying-glass` should be used for all other concepts (i.e. magnify, zoom, inspect, analyze, observe, etc.).

Closing this issue.
