### ISSUE TITLE
Icons as a font

### ISSUE THREAD

**Issue by spatialdude** [Esri/calcite-ui-icons#56]
Hi

Could the calcite icons be made available as a TrueType font? This would be very usefully for rendering the fonts in an app and taking advantage of the font rendering environment.

**Comment by paulcpederson** [comment]
@spatialdude are you referring to an ios/android app or a web app?

**Comment by spatialdude** [comment]
@paulcpederson I'm referring to native apps, in this case more specifically AppStudio apps which s run on iOS/Andorid/macOS/Windows/Linux. TrueType is supported in AppStudio apps on all of these platforms.

**Comment by paulcpederson** [comment]
OK, yeah we can investigate this. I am concerned that app download times would severely lengthen if we included all of these glyphs in a font, yeah? There are 2,430 glyphs today.

**Comment by spatialdude** [comment]
The size is a good point. Have you done any estimations on what the entire set as a TTF might be?

In the case of app like Survey123, for ease of maintenance I'd considered including the entire set in SVG format but found that was too large, so we only pull in the ones that are specifically needed.

**Comment by spatialdude** [comment]
@paulcpederson Using FontForge, I experimented and created a script to convert the SVG files into font files to see how large they would be.

I created two font files for the **Calcite** family -
* calcite.ttf (Regular weight from standard icons)
* calcite-f.ttf (Bold weight from "filled" icons)

They ended up very compact and smaller than the SVG input files - 95Kb and 74Kb respectively.

Each font contains 421 unique icon characters which I put into the Unicode range starting at U+E000.

Only the -32 and -32-f resolution files were used, as these are the highest resolution. 

As fonts, I found they scaled very well, even up to 200 point size. As they are two weights in the same family, it's also very easy to switch between filled and unfilled by simply selecting the font as bold or normal weight. 

The sample TTF files are available here to try out - [calcite.zip](https://github.com/Esri/calcite-ui-icons/files/3435797/calcite.zip)

![image](https://user-images.githubusercontent.com/7235583/61953040-bf6f3f80-aff8-11e9-8f4e-b0339e6541b0.png)

![image](https://user-images.githubusercontent.com/7235583/61953080-d57d0000-aff8-11e9-95a4-20ef50a20abb.png)

**Comment by paulcpederson** [comment]
@spatialdude Cool. Yeah this amount of weight is probably fine in a mobile app where you have a single install. Would not work well in a web context, though.

Unless you're displaying icons frequently at 32px or larger, it may be better to use a smaller size as these 32px ones won't necessarily scale _down_ well. All of the sizes will grow larger as they are vector data (even when in a font). Best approach would probably be to create subsets of these and have fonts for each size/variant containing only the glyphs you actually need.

**Comment by julio8a** [comment]
Closing this out for now. Re-open if you feel there is more conversation needed around this topic.

**Comment by dotMorten** [comment]
>  Would not work well in a web context, though.

The specific ask was for a non-web app context though. I'm finding it really hard to use the svg files in apps - it's a HUGE add to an app, compared to the font, not to mention svg rendering seems to perform really poorly with inconsistent rendering on each platform. However font rendering works consistently and fast on all platforms.
If we ever want to bring calcite icons to native apps, a font-approach is definitely the best approach.
