### ISSUE TITLE
App launcher

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-ui-icons#6]
We don't have app launcher in the library.

![image](https://user-images.githubusercontent.com/6144462/44161570-94534080-a072-11e8-94ea-8677d31cbab2.png)

**Comment by asangma** [comment]
"App **Launcher**"

**Comment by johnmgriffith** [comment]
We'll be putting up app-launcher in our next release.

**Comment by julio8a** [comment]
published in the latest release [v1.1.2](https://github.com/Esri/calcite-ui-icons/releases/tag/v1.1.2). Closing this out.
