### ISSUE TITLE
caret-16 seems too large for most contexts

### ISSUE THREAD

**Issue by mitc7862** [Esri/calcite-ui-icons#68]
The caret icon seems too large. Would it be possible to resize it similarly to the chevron-16 icon?

Here is a screenshot of our in progress UI with annotations. Please disregard the weird placeholder images.
![image](https://user-images.githubusercontent.com/12564905/62168226-e4560200-b2d9-11e9-816e-8d2f3d1b43cb.png)

**Comment by macandcheese** [comment]
Agree with this, it would be great if the caret was just a "closed path" chevron with matching dimensions, since they are often used side by side in an interface as shown above.

**Comment by KatelynSeitz** [comment]
@mitc7862 @macandcheese awesome, good to know! We will make this adjustment in the next release.

**Comment by TheBlueDog** [comment]
We could use smaller version as well. For now, we just use CSS to resize the SVG. I think down to either 12x12 or 10x10.

**Comment by KatelynSeitz** [comment]
Looking at the caret-square assets. Should these carets be scaled down as well or are they used for something else entirely?  
lmk @mitc7862 @macandcheese @TheBlueDog 

![image](https://user-images.githubusercontent.com/29716057/62645570-55606f80-b901-11e9-9a86-63184bc68378.png)

**Comment by TheBlueDog** [comment]
@KatelynSeitz  I haven't found a use for those. I've tried them in the past but the square makes them too dominant over the label they are next to, and the pattern in other apps seems to be using the caret/chevron.

**Comment by macandcheese** [comment]
I think they are probably used less frequently, but makes sense for them to be updated to use the new shape so, if they are used, at least it's the same shape.

**Comment by TheBlueDog** [comment]
In regards to the scaled down version of the caret/chevron, we prefer to use a single icon and then do a nice CSS animation to show the rotation as module is open/closed. So having them centered on the canvas will keep that movement smooth.

**Comment by KatelynSeitz** [comment]
For sure. Working on simplifying the following four concepts to just a single centered asset in each size to rotate like below:

![caret-animation](https://user-images.githubusercontent.com/29716057/62647855-619afb80-b906-11e9-8df2-851bc57cfec2.gif)

**Comment by TheBlueDog** [comment]
Yes! :)

**Comment by asangma** [comment]
Hmmm...are we retaining the up, down, left, right ones?

**Comment by asangma** [comment]
That is to say, I like the ability to rotate a centered icon. It's also good to have the different SVGs. So regardless of which direction the icon starts out pointing, flipping it is always 180º.

Assuming we're not doing scale transforms...?

Also we currently have stuff that toggles the path depending on state, and while it'd be cool to refactor to do transforms instead, we could use a minute to make changes. :)

**Comment by KatelynSeitz** [comment]
For this up-coming release, we can simply update the positioning and keep the four options. 

But ideally, we wouldn't need more than one asset for each if they are perfectly rotate-able, correct? It would just take a transition period to refactor the states, flips, transforms, etc?

**Comment by TheBlueDog** [comment]
@KatelynSeitz I think that's a good idea. That way it won't create more work for app teams that are using any of the other options if you were to remove them.

**Comment by macandcheese** [comment]
Yeah I'd kind of prefer to just leave all four orientations as individual glyphs? 

Great if folks want to css to rotate the "up" caret for animations - but leaving all four makes using them as sketch symbols easier for static comps, or to use code without *having* to use css still an option. Thoughts?

**Comment by asangma** [comment]
@macandcheese 💯 💥 🚀

**Comment by johnmgriffith** [comment]
Great, so what we'll put in our new large release is all 4 sizes, but they will all be centered, so that they should all be able to be rotated or flipped without issue.

**Comment by TheBlueDog** [comment]
@johnmgriffith What's the 4th size?

**Comment by KatelynSeitz** [comment]
probably meant all 4 orientations ie:
arrow-right, arrow-left, arrow-up, arrow-down

**Comment by johnmgriffith** [comment]
Yeah, that's what I meant

**Comment by paulcpederson** [comment]
✨ 🥕  ✨ 

📦 v2.5.0
