### ISSUE TITLE
Should cursor-marquis be renamed to cursor-marquee? 

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-ui-icons#69]
I wasn't sure if it's a typo or if I'm just unfamiliar with that spelling. 😄 

https://esri.github.io/calcite-ui-icons/#cursor-marquis

**Comment by asangma** [comment]
I dunno @jcfranco. It is a pretty noble icon. LOL

But srsly. It should be marquee.

![image](https://user-images.githubusercontent.com/12503298/63445234-daad4f00-c3ec-11e9-9f42-00c315d3210b.png)

@KatelynSeitz @johnmgriffith

**Comment by johnmgriffith** [comment]
You are definitely right! We are working through a large number of Calcite UI changes, and this is on our list of items to fix. Thanks!

**Comment by paulcpederson** [comment]
Fixed in 2.5.0, we must bid adieu to the marquis of cursor

![out_9 49 35_am](https://user-images.githubusercontent.com/1031758/64467326-6cdf7380-d0cc-11e9-8cfa-eb404a50afd8.gif)
