### ISSUE TITLE
Remove sprites/sprite generation

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-ui-icons#71]
All of the sprite files are over 150kb now, making them too large to load in a performant way in the browser. I think we should remove the sprites so we're not encouraging poor performance practices.

**Comment by ffaubry** [comment]
I agree that we are downloading a bunch of icons for nothing. An app like Dashboard is probably using 10-15 icons max.

Are you suggesting that we should pull individually the icons used in the app? Just curious what you have seen as good practice out there.

**Comment by paulcpederson** [comment]
I think most frameworks will have a plugin in their ecosystem that makes inline icons a bit easier to manage. For ember something like: https://github.com/minutebase/ember-inline-svg

We could add a utility to the exported JS like carbon does to generate an svg from path data if that would help: https://github.com/carbon-design-system/carbon/tree/master/packages/icons#vanilla

**Comment by ffaubry** [comment]
@paulcpederson The inline-svg ember ext is inlining the svg each time it's referenced.
Not good...

We will basically add the icons we use in our build definition and create a sprite file just for our build...
Not a big deal.
I don't see a good solution from any angle. Either we get big sprite files that contain a bunch of unused icons for most apps... Or each app need its own packaging of resources...
I'm fine going with 'it's an app responsability'.

Question for @jcfranco and @patrickarlt :
Will calcite-ui-icons being in calcite-components or inside app-components? Exposed in a way that calcite components app could access them?

**Comment by jcfranco** [comment]
Right now, icons are an NPM dependency and any app can pull them in independently and use as they see fit. I don't think we'd want to expose them through either components project. WDYT @patrickarlt?

Having said that, if we served the icon path data individually, we could introduce an icon component that dynamically loads (and caches) its content. Not sure what this would mean for spritesheet users though.

**Comment by ffaubry** [comment]
I think it would be a great idea if we could have an CalciteIcon component... I will let @patrickarlt decides.
In Dashboard we have such component:

<Icon name="x-16" angle="..." rtlName="..." />

Note: 
- rtlName (opt) is the icon used if the rtl is on.
- angle (opt) allows to rotate the angle by 0, 45, 90, 180 degrees

**Comment by paulcpederson** [comment]
> Having said that, if we served the icon path data individually, we could introduce an icon component that dynamically loads (and caches) its content. Not sure what this would mean for spritesheet users though.

[This pr](https://github.com/Esri/calcite-ui-icons/pull/70) will enable linking to a single icon's path data like `import { arrowLeft16 } from "@esri/calcite-ui-icons/js/arrowLeft16.js";` This hasn't been merged yet, so if we want to change the syntax to make it easier for this use case let me know

**Comment by jcfranco** [comment]
@paulcpederson That's perfect! I can prototype something once it's merged. 😄

**Comment by paulcpederson** [comment]
@jcfranco that change is published in v2.4.0

**Comment by jcfranco** [comment]
we haz prototape: https://github.com/Esri/calcite-components/tree/jcfranco/proto-calcite-ui-icon

<img width="369" alt="Screen Shot 2019-08-14 at 9 13 39 AM" src="https://user-images.githubusercontent.com/197440/63037635-4a16c200-be74-11e9-983c-c23eab582d66.png">

```html
<calcite-tab>
  <h2>Default</h2>
  <calcite-ui-icon icon="aZ"></calcite-ui-icon>
  <calcite-ui-icon icon="basemap"></calcite-ui-icon>
  <calcite-ui-icon icon="camera"></calcite-ui-icon>

  <h2>Size can be 16px, 24px or 32px</h2>
  <calcite-ui-icon icon="aZ" size="16"></calcite-ui-icon>
  <calcite-ui-icon icon="basemap" size="24"></calcite-ui-icon>
  <calcite-ui-icon icon="camera" size="32"></calcite-ui-icon>

  <h2>Filled</h2>
  <calcite-ui-icon icon="aZ" filled></calcite-ui-icon>
  <calcite-ui-icon icon="basemap" filled></calcite-ui-icon>
  <calcite-ui-icon icon="camera" filled></calcite-ui-icon>
</calcite-tab>
```

**Comment by paulcpederson** [comment]
@jcfranco nice! This idea is really cool. We'll have to find a better location to pull the icons from though as on-premise products won't be able to access `unpkg.com`. We could theoretically copy just the js icon files over alongside the bundle or something, maybe?

**Comment by jcfranco** [comment]
Yeah, I went w/ unpkg for now because I ran into some issues where dynamic imports to the path data weren't resolving correctly. I also need to look more into dynamic imports to make sure it'll work consistently. 🛠

**Comment by julio8a** [comment]
Closing this one out. Please re-open if needed.
