### ISSUE TITLE
Drag and drop icon

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#72]
We could us an icon specifically for drag interactions.

Something like the double vertical handle here
![image](https://user-images.githubusercontent.com/12503298/62903972-5b978700-bd19-11e9-828f-b76d5c925445.png)

**Comment by asangma** [comment]
Thank!

**Comment by KatelynSeitz** [comment]
Agreed! This would be a great addition. Let's get a Workfront request in.

**Comment by asangma** [comment]
Thanks @KatelynSeitz!

**Comment by KatelynSeitz** [comment]
Release delayed until Tuesday.

**Comment by paulcpederson** [comment]
https://esri.github.io/calcite-ui-icons/#drag Thanks @KatelynSeitz and @johnmgriffith !

**Comment by asangma** [comment]
Yew!
[insert dragon gif]
