### ISSUE TITLE
Circle Filled - it's ok to fill the circle.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#73]
Hey there. Seems like it's all right to fill the circle in this icon.
![image](https://user-images.githubusercontent.com/12503298/62904461-53404b80-bd1b-11e9-97f0-7d15f4fc9ecb.png)

The hashes do follow the single-line approach, but seems like we can probably vary from that a little here.

**Comment by johnmgriffith** [comment]
Definitely. We are currently working on a Calcite UI 2.0 that takes out unnecessary icons like this. The hashing is almost never needed, so we are dealing with a number of icons that use that treatment.

**Comment by asangma** [comment]
coo...thanks!
