### ISSUE TITLE
Request : Date icon

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#75]
We currently have a calendar icon. While this can represent things like a date picker interface, it would also be good to have slightly smaller and simpler icon for "date".

In a lot of cases, we are asking the user to "pick a date" as opposed to "open a calendar". Sometimes, we also need a way to indicate that something "is a date" or "is of type date", e.g. when showing a list of attributes from a data table.

So a "date" icon might like look like the one on the right:
![Screen Shot 2019-08-21 at 8 09 37 AM](https://user-images.githubusercontent.com/12503298/63444501-93728e80-c3eb-11e9-9efe-56515e51e071.png)

Here's an example of where the date icon would be used:
![image](https://user-images.githubusercontent.com/12503298/63444609-cae13b00-c3eb-11e9-853e-4f978d41ad98.png)

In this case, the user is setting the formatting for this date attribute.

Here's what it looks like with the calendar icon:
![image](https://user-images.githubusercontent.com/12503298/63444698-f6642580-c3eb-11e9-987e-083aac8bcc43.png)

Please ignore the # icons. That'll be a different issue. :)

**Comment by asangma** [comment]
Alternatively, we could update the calendar icon.

**Comment by asangma** [comment]
@KatelynSeitz @johnmgriffith

**Comment by asangma** [comment]
Also, it's easy to confuse the calendar icon with the data table icon. :)

**Comment by macandcheese** [comment]
To avoid usage fragmentation (folks using the one intended for single dates for calendar, and vice versa) across apps, it would be nice to find "one calendar icon to rule them all", so to speak - simplify the current one so it works for both use cases, as I agree having all those date cells at small scales can be a bit much.

**Comment by KatelynSeitz** [comment]
Yes, one calendar icon to serve both use-cases would be a great! We can make this change in our upcoming large release where we are addressing improvements like these across the set. Thanks!

![image](https://user-images.githubusercontent.com/29716057/63460014-8dd87100-c40a-11e9-9e6b-71e949243864.png)

**Comment by asangma** [comment]
Sweet! Thanks! @KatelynSeitz Do you need me to make a Workfront request?

**Comment by KatelynSeitz** [comment]
Since this one is an update to an existing icon, no Workfront request needed. Thanks for checking! We are hoping to make this big release early next week.

**Comment by asangma** [comment]
Sweet! Thanks.

**Comment by julio8a** [comment]
nice update!

**Comment by KatelynSeitz** [comment]
Release delayed until Tuesday.

**Comment by paulcpederson** [comment]
Another problem solved by the dream team in 2.5.0 🙌 

https://esri.github.io/calcite-ui-icons/#calendar

**Comment by asangma** [comment]
Y'all rock!
