### ISSUE TITLE
Request : Datatype icons

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#76]
[edited]
We would like icons for a few of the datatypes:

- Date (already happening #75)
- String
  - some are using the description icon for this
 - The `abc` icon is English specific. Is that OK?
- Number
  - I tried using the # symbol for this, and that seemed to make sense, but yeah...
- Integer
  - Some are using the SUM symbol for this but that seems weird.
  - [According to wikipedia](https://en.wikipedia.org/wiki/Integer) the symbol for integer is the Zahlen.
- Boolean
  - We don't really have this type in our system (that I know of), but enhancements will allow for a datatype that is semantically a boolean.

I understand that these icons may already exist in a different style, so if we can leverage any prior concept approvals, cool!

@johnmgriffith @KatelynSeitz @paulcpederson

**Comment by asangma** [comment]
Note: we can likely ignore more nuanced datatypes like float, double, decimal, etc.

**Comment by johnmgriffith** [comment]
We designed a "123" a while ago for another concept, but it was never used and therefore never put in the set. Would this work better for "Number" or "Integer"?

![image](https://user-images.githubusercontent.com/30184050/64049498-e2c26880-cb29-11e9-9cf7-9aac15e86598.png)

**Comment by KatelynSeitz** [comment]
String: `abc` has been approved to be used. 

@asangma Let's get a Workfront request going for a Zahlem `Integer` symbol and `Boolean`.

**Comment by asangma** [comment]
@CodeBarker Did we say that our attributes list still needs an "integer" icon?
That is to say will the "Number" concept above work for both number and integer?

re: boolean
I will put in a request.

### Typography
I was thinking that with datatypes, when using characters as part of the icon, it may be good to base the character style on monospace. Seems closer to "data" and also helps separate it from actual strings in the interface.

**Comment by asangma** [comment]
Request submitted on Workfront.

**Comment by CodeBarker** [comment]
Yup we'll need one.  

I think we'll potentially need one for number and integer in the future but for now one icon for both would suffice

**Comment by KatelynSeitz** [comment]
yup good suggestion @asangma. We can use the same monospace type style for `string`, `int`, and `bool`

**Comment by asangma** [comment]
![bmo-dancing](https://user-images.githubusercontent.com/12503298/66145025-c731fe00-e5be-11e9-8e0d-cca23e01ee85.gif)

**Comment by johnmgriffith** [comment]
`number` also was included in this release, an additional monospace type icon.

This issue is resolved in #92

**Comment by johnmgriffith** [comment]
New icons in release 2.5.3
