### ISSUE TITLE
Drop the Compass-north-circle icon

### ISSUE THREAD

**Issue by johnmgriffith** [Esri/calcite-ui-icons#78]
We have two compass icons, one called "compass-north-circle", and another called "compass-circle". 
We had both because the circles were slightly different sizes, but I think altogether it's unnecessary to have both, so we are considering consolidating them into just "compass-circle". That way we have only one, centered asset.

So from this:
![image](https://user-images.githubusercontent.com/30184050/63549869-30b1ed80-c4e6-11e9-8966-a6d65acf792c.png)

to this:
![image](https://user-images.githubusercontent.com/30184050/63549803-06603000-c4e6-11e9-9bf4-44646f209b00.png)

Would this cause any issues?

**Comment by asangma** [comment]
I believe the north on is for "compass" and the rotated one is like for "direction" or "bearing"...tracking or something...? It would be good to check in with peeps from some of the fields apps.

**Comment by TheBlueDog** [comment]
The second version was added for Tracker because we rotate it based on the bearing of the track point collected. The other would wobble and cause alignment issues. I thought `compass-north-circle` was the corrected one, since that's at 0°. 

@jrowlingson You see any impact for our apps?

**Comment by johnmgriffith** [comment]
Yeah, you can see from the screenshot that it was the other way around. `compass-north-circle` as it stands will wobble if rotated, but `compass-circle` is rotated at a 45° angle.

This adjustment would bring it to one asset, that won't wobble, angled at 0°, with the name `compass-circle`

**Comment by johnmgriffith** [comment]
@TheBlueDog @jrowlingson 

So are we good to move forward with this change?

**Comment by TheBlueDog** [comment]
Looks good to me.

**Comment by asangma** [comment]
👍

**Comment by johnmgriffith** [comment]
Awesome, we'll make this change in our upcoming big release.
