### ISSUE TITLE
Undo, redo, reset

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#8]
Add undo and redo arrows.
We currently have the [reset](https://github.com/Esri/calcite-ui-icons/blob/master/icons/reset-16.svg) icon. 

![image](https://user-images.githubusercontent.com/12503298/44427414-5fe5f580-a546-11e8-84d8-4d3b087c2d91.png)

Not sure if this overlaps too much with what "undo" and "redo" concepts would look like.

**Comment by johnmgriffith** [comment]
These icons have been uploaded in the latest release, 1.1.3. We created undo and redo, and updated our current reset icon.

Closing this issue.
