### ISSUE TITLE
Request : "what's new" or "new thing"

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#81]
We could use a "what's new" or "updates" icon.
In the new map viewer, we will have an interface that informs users what our upcoming capabilities are.

Something like this
![image](https://user-images.githubusercontent.com/12503298/63874943-55d7ad80-c977-11e9-8102-6e0cd8db3195.png)

@paulcpederson @KatelynSeitz 

Taken from YouTube Studio beta.

**Comment by asangma** [comment]
Aight...I'll go with the megaphone. Would it make sense to add "new" as a keyword for megaphone?

**Comment by KatelynSeitz** [comment]
Can do.

**Comment by johnmgriffith** [comment]
Closing this issue
