### ISSUE TITLE
Enhancement : Speech bubble design update

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#82]
The family of speech bubble icons seems a bit out of place next to the other icons.

In general, the icons nicely utilize straight lines and rectangular silhouettes. Would we be able to update the speech icons to match that look.

I am also thinking about new map viewer and that we'll have a "give feedback" button from the left menu bar, so having an icon that aligns visually would be cool.

**Comment by johnmgriffith** [comment]
Updated designs:

![image](https://user-images.githubusercontent.com/30184050/63984198-eb119980-ca7e-11e9-9cca-a560d58fb3ec.png)

**Comment by paulcpederson** [comment]
🎉  2.5.0  🎉

**Comment by asangma** [comment]
🙉

**Comment by asangma** [comment]
❤️
