### ISSUE TITLE
Media icons feel too small?

### ISSUE THREAD

**Issue by johnmgriffith** [Esri/calcite-ui-icons#83]
Compared to a lot of our other icons, the pause, play, next, previous, etc. icons are quite a bit smaller than other icons. They have significantly more padding than other icons. Has that been an issue for any of you?

@asangma @TheBlueDog @macandcheese @paulcpederson 

![image](https://user-images.githubusercontent.com/30184050/63967580-95bf9300-ca52-11e9-98dc-b6ffef5599f6.png)

![image](https://user-images.githubusercontent.com/30184050/63967621-ab34bd00-ca52-11e9-8c61-bf434c4f5365.png)

**Comment by TheBlueDog** [comment]
Right now we don't have a use for any of those in our apps. But in general, having consistent padding for all the icons is a nice idea.
