### ISSUE TITLE
Lightbulb icon opens blank in Illustrator and Photoshop

### ISSUE THREAD

**Issue by spatialdude** [Esri/calcite-ui-icons#84]
Hi

The lightbulb SVG file opens blank in Illustrator and Photoshop.

**Comment by johnmgriffith** [comment]
We've noticed this issue with some of our icons. It appears that SVG-O is sometimes deleting paths and changing the color mode from RGB to CMYK.

@paulcpederson do you know why this might be happening?

**Comment by paulcpederson** [comment]
I think this is due to the bump in SVGO: https://github.com/svg/svgo/issues/1138 

I will play around with the optimization lib and see if there is an option to turn the spaces off.

**Comment by johnmgriffith** [comment]
Thanks! Let me know what you learn. We want to apply whatever configurations to our personal SVG-O settings.

**Comment by spatialdude** [comment]
I have found that if the icon shows blank in Adobe apps then it also won't render correctly in our apps. Strange thing is the macOS file preview does render them and so does opening them in a Microsoft app then exporting.

**Comment by arjavbadjatiya** [comment]
@paulcpederson Not sure if this is related:
(This is what is happening when I download the refresh-16 or refresh-24 svg and add it to Sketch)
<img width="428" alt="Screen Shot 2019-09-04 at 11 21 27 AM" src="https://user-images.githubusercontent.com/29237960/64280664-73bc8980-cf06-11e9-9087-142639b53c98.png">

This is how the layer list looks:
<img width="189" alt="Screen Shot 2019-09-04 at 11 21 35 AM" src="https://user-images.githubusercontent.com/29237960/64280670-77501080-cf06-11e9-9f4c-85016f37afed.png">

This is not happening with other previously downloaded SVGs.

**Comment by paulcpederson** [comment]
Yep, pending pr will fix all of this

**Comment by paulcpederson** [comment]
@arjavbadjatiya fixed, go ahead and try to download again from the docs and it should hopefully work

**Comment by arjavbadjatiya** [comment]
It works. Thanks @paulcpederson !
