### ISSUE TITLE
Request : Arcade Expression

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#89]
Did we already discuss adding the Arcade icon to this library?

**Comment by KatelynSeitz** [comment]
@asangma Perhaps. I remember a while back there was some discussion around adding one of our product logos as a tool icon, however, since this set is public, we decided to avoid logos as icons.

**Comment by asangma** [comment]
@KatelynSeitz could i get an svg icon set to be used in our unternal apps?

**Comment by KatelynSeitz** [comment]
@asangma for sure. Do you have access to this product logo repo? https://github.com/ArcGIS/esri-product-logos/tree/master/ArcGIS%20Arcade/SVG%20Glyph%20-%20Small%20Scale%20Implementation%20Only
If so, I can export and add all three sizes here.

**Comment by KatelynSeitz** [comment]
@asangma 16, 24, and 32px logo assets added to the [Product Logo Repo](https://github.com/ArcGIS/esri-product-logos/tree/master/ArcGIS%20Arcade/SVG%20Glyph%20-%20Small%20Scale%20Implementation%20Only).
Feel free to reach out if anything else is needed on these.

**Comment by asangma** [comment]
Thanks @KatelynSeitz seems like I no longer have access to that repo. :(

**Comment by johnmgriffith** [comment]
@asangma Hmm, alright, we'll look into that. In the meantime, I'll send you the SVGs directly.

**Comment by asangma** [comment]
Thanks!
