### ISSUE TITLE
Package version out of sync with release

### ISSUE THREAD

**Issue by crowjonah** [Esri/calcite-ui-icons#91]
We're not able to bring in the latest release because yarn complains:

```
Missing yarn packages: 
Package: calcite-ui-icons
  * Specified: git+ssh://git@github.com/esri/calcite-ui-icons.git#v2.5.2
  * Installed: 2.5.1
```

**Comment by paulcpederson** [comment]
thanks @crowjonah this should be fixed now

**Comment by crowjonah** [comment]
Sorry to be a thorn in your side, but bumping the package version doesn't appear to have solved it. We don't have any pressing need to consume this release, so don't worry about it on our behalf. For reference, here's what I'm seeing now in the `git fetch --tags` phase of a `yarn install`, reproduced in a clean new app:
```
Output:
From ssh://github.com/esri/calcite-ui-icons
 ! [rejected]        v2.5.2     -> v2.5.2  (would clobber existing tag)
```

**Comment by paulcpederson** [comment]
Yeah, you may need to do a ‘git tag -d v2.5.2‘ and fetch again. If that doesn't work you can just wait for 2.5.3 which should come out today
